website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, current_app, session
from .models import User, FamilyMember, Photo
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user
import requests
import random
import json
from .models import Favorite, Family
from . import db
from sqlalchemy import func
from .code_generator import generate_code
import string
import time
from werkzeug.utils import secure_filename
import os


auth = Blueprint('auth', __name__)


@auth.after_request
def add_header(response):
    session.permanent = False
    response.headers["Cache-Control"] = "no-store, max-age=0"

    return response


@auth.route('/main')
def main():
    # csrf_token = generate_csrf()
    # session['csrf_token'] = csrf_token
    return render_template('main.html', css_file='styles.css')


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember=True)
                return redirect(url_for('auth.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist. Please sign up to continue',
                  category='error')

    return render_template("login.html", user=current_user)


@auth.route('/home')
@login_required
def home():
    return render_template('home.html', user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.main'))


@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('first_name')
        last_name = request.form.get('last_name')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 4 characters', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 2 character', category='error')
        elif password1 != password2:
            flash('Error, password mismatch', category='error')
        elif len(password2) < 7:
            flash('Password must be more than 7 characters', category='error')
        else:
            new_user = User(email=email, first_name=first_name, last_name=last_name,
                            password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('auth.home'))

    return render_template("signup.html", user=current_user)


@auth.route('/movies', methods=['GET', 'POST'])
@login_required
def movies():

    random_page = random.randint(0, 100)

    url1 = "https://api.themoviedb.org/3/discover/movie?api_key=28dd9fa4c4a210cd3dc589981c8fb66a&language=en-US&region=US&sort_by=popularity.desc&include_adult=false&include_video=false&page=" + \
        str(random_page) + "&with_watch_monetization_types=flatrate"
    request1 = requests.get(url1)

    data1 = request1.json()
    titles = data1.get('results')
    random_title = random.choice(titles)
    random_id = random_title.get('id')
    print(random_id)

    random_title_image = random_title.get('poster_path')
    url_append = "https://image.tmdb.org/t/p/original"
    full_path_random_title_image = url_append + random_title_image
    print(full_path_random_title_image)

    over_view = random_title.get('overview')
    full_overview = over_view[:20000]
    short_over_view = over_view[:135]

    title = random_title.get('title')

    print(title)

    print(over_view)

    return render_template("movies.html", user=current_user, full_path_random_title_image=full_path_random_title_image, title=title, over_view=over_view, full_overview=full_overview, short_over_view=short_over_view)


@auth.route('/add_favorite_movie', methods=['GET', 'POST'])
@login_required
def add_favorite_movie():
    title = request.form['movie_title']
    image = request.form['movie_image_url']
    user_id = request.form['current_user']
    favorite_exists = Favorite.query.filter_by(
        user_id=current_user.id, title=title).first()
    if favorite_exists:
        flash('title as already been added to your Playlst', category='error')
        return redirect(url_for('auth.movies'))
    global favorites
    new_favorite = Favorite(title=title,
                            user_id=current_user.id, image=image)
    if new_favorite:
        db.session.add(new_favorite)
        db.session.commit()
        flash('Added to PLaylst!', category='success')
        return redirect(url_for('auth.movies'))

    return render_template('favorites.html', user=current_user, favorites=favorites)


@auth.route('/tvshows', methods=['GET', 'POST'])
@login_required
def tvshows():
    random_page = random.randint(0, 50)

    url2 = "https://api.themoviedb.org/3/discover/tv?api_key=28dd9fa4c4a210cd3dc589981c8fb66a&language=en-US&sort_by=popularity.desc&page=" + \
        str(random_page) + "&timezone=America%2FNew_York&include_null_first_air_dates=false&watch_region=US&with_watch_monetization_types=flatrate&with_status=0&with_type=0"

    request1 = requests.get(url2)

    data1 = request1.json()

    titles = data1.get('results')
    random_title = random.choice(titles)
    random_id = random_title.get('id')

    print(random_id)

    random_title_image = random_title.get('poster_path')
    url_append = "https://image.tmdb.org/t/p/original"
    full_path_random_title_image = url_append + random_title_image
    print(full_path_random_title_image)

    over_view = random_title.get('overview')

    title = random_title.get('name')

    print(title)

    print(over_view)

    return render_template("tvshows.html", user=current_user, full_path_random_title_image=full_path_random_title_image, title=title, over_view=over_view)


@auth.route('/add_favorite_tv_show', methods=['GET', 'POST'])
@login_required
def add_favorite_tv_show():
    title = request.form['tv_show_title']
    image = request.form['tv_show_image_url']
    user_id = request.form['current_user']
    favorite_exists = Favorite.query.filter_by(
        user_id=current_user.id, title=title).first()
    if favorite_exists:
        flash('title as already been added to playlst', category='error')
        return redirect(url_for('auth.tvshows'))
    new_favorite = Favorite(title=title, image=image, user_id=current_user.id)
    if new_favorite:
        db.session.add(new_favorite)
        db.session.commit()
        flash('Added to Playlst!', category='success')
        return redirect(url_for('auth.tvshows'))

    return render_template('favorites.html', user=current_user, favorites=favorites)


@auth.route('/delete_favorite', methods=['POST'])
@login_required
def delete_favorite():
    try:
        title = request.form['title']
        image = request.form['image']
        user_id = request.form['current_user']
        print(title, image, user_id)
        favorite = Favorite.query.filter_by(title=title, image=image, user_id=current_user.id).filter(
            func.lower(Favorite.title) == func.lower(title), func.lower(Favorite.image) == func.lower(image)).first()
        if favorite:
            db.session.delete(favorite)
            db.session.commit()
            flash("Title has been removed", category='success')
        else:
            flash("Title not found", category='error')
    except Exception as e:
        flash("Error while deleting favorite", category='error')
    return redirect(url_for('auth.favorites'))


@auth.route('/favorites', methods=['GET', 'POST'])
@login_required
def favorites():
    user = current_user
    return render_template('favorites.html', user=current_user.id, favorites=current_user.favorites)


@auth.route('/group_code', methods=['GET', 'POST'])
@login_required
def group_code():
    user = current_user
    code = current_user.code
    return render_template('group_code.html', user=current_user, code=code)


@auth.route('/group_hub', methods=['GET', 'POST'])
@login_required
def group_hub():
    member_photo = current_user.photo
    family = Family.query.filter_by().first()
    return render_template('group_hub.html', user=current_user, family=family, member_photo=member_photo)


@auth.route('/generate_code', methods=['POST', 'GET'])
@login_required
def generate_code():
    user = current_user
    family = user.family

    # Check if user has a family
    if not family:
        code = ''.join(random.choices(
            string.ascii_uppercase + string.digits, k=6))
        # name = request.form['group_name']
        family = Family(code=code)
        family.members.append(user)
        db.session.add(family)
        db.session.commit()
        flash("Code generated successfully", category='success')

    # Update family name if request contains a new name
    elif request.method == 'POST' and 'group_name' in request.form:
        family.name = request.form['group_name']
        db.session.commit()
        flash("Group name updated!", category='success')

    return render_template('group_hub.html', user=current_user, family=family)


@auth.route('/add_member', methods=['GET', 'POST'])
@login_required
def add_member():
    user = current_user
    # if request.method == 'POST':
    code = request.form['code']
    family = Family.query.filter_by(code=code).first()

website/templates/favorites.html
{% extends "base.html" %} 
{% block title %}My Playlist{% endblock %} 
{% block content %}  
  
  <h1 color="#000000" align="center"></h1>
  <h1>My Playlist</h1>
  <div class="row row-cols-1 row-cols-md-2 g-4 justify-content-center">
    {% for favorite in favorites %}
    <div class="col-6">
      <div class="card">
        <form method="post" action="{{ url_for('auth.delete_favorite') }}">
          <input type="hidden" name="title" value="{{ favorite.title }}" />
          <input type="hidden" name="image" value="{{ favorite.image }}" />
          <input type="hidden" name="current_user" value="{{ current_user }}"/>
          <button class="delete-btn" type="submit">❌</button>
        </form>
        
        <img
          src="{{ favorite.image }}"
          alt="{{ favorite.title }}"
          style="height: 100%; width: 100%; object-fit: cover;"
          class="title_image"
        />
        <h5>{{ favorite.title }}</h5>
      </div>
    </div>
    {% endfor %}
  </div>



<style>
    h2 {
      margin-top: 30px;
      border-radius: 5px;
      font-family: BaronNeue, classic sans serif;
      font-size: 24px;
      font-weight: bold;
      color: #66aa33;
    }
    .card {
      border-radius: 35px;
      background-color: white;
      position: relative;
      padding-bottom: 0px;
      padding-top: 0px;
    }
    .card-header {
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      padding: 10px;
      background-color: rgba(255,255,255,0.7);
      z-index: 1;
    }
    .card-body {
      padding: 30px;
    }
    .col {
      margin-bottom: 20px;
      margin-left: 5px;
    }
    .card-text {
      font-size: 16px;
    }
    .delete-btn {
      position: absolute;
      top: -10px;
      right: 5px;
      background-color: transparent;
      color: white;
      border: none;
      border-radius: 50%;
      width: 30px;
      height: 30px;
      font-size: 20px;
      line-height: 20px;
      text-align: center;
      padding: 0;
      cursor: pointer;
    }
    .card {
      position: relative;
    }
    .title_image {
      border-top-left-radius: 35px;
      border-top-right-radius: 35px;
    }
  </style>


{% endblock %}

website/templates/group_code.html
{% extends "base.html" %}
{% block title %}Group Code{% endblock %}

{% block content %}
<div class="container">
  {% if current_user.family.code  %}
    <h1>Code:</h1>
    <h2>{{ current_user.family.code }}</h2>
  {% else %}
    <h1>No code generated yet</h1>
    <a href="{{ url_for('auth.group_hub') }}"> <button> Group Hub </button> </a>
  {% endif %}
</div>

<style>

  h1 {
    font-size: 50px;
    font-weight: bold;
  }
  h2 {
    display: inline-block;
    padding: 5px 10px;
    border-radius: 5px;
    font-size: 24px;
    font-weight: bold;
    padding: 1px; /* add some padding to make the background more visible */
    text-align: center;
  }

  h3 {
    font-size: 16px;
    font-weight: bold;
  }
  img {
    display: block;
    margin-left: auto;
    margin-right: auto;
    padding: 15px;
  }
  .text-center {
    text-align: center;
  }
  
  button {
    background-color: #007bff;
    color: white;
    padding: 1px 30px;
    border-radius: 4px;
    border: none;
    margin-top: 20px;
    cursor: pointer;
    font-size: 20px;
    font-weight: bold;
  }
  .card {
    border-radius: 15px;
    background-color: white;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
    position: relative;
  }
  .card-body {
    padding: 0;
  
  }
  .col {
    margin-bottom: 20px;
  }
  .card-title {
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100%;
    padding: 10px;
    background-color: rgba(255,255,255,0.7);
    text-align: center;
  }
  
  .card-text {
    font-size: 16px;
  }


</style>
{% endblock %}

website/templates/group_hub.html
{% extends "base.html" %} {% block title %} Group Playlst {% endblock %} {%block
content %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <br/>
    <title>Group</title>
    <style>
      
      .container {
        margin: 0 auto;
        text-align: center;
      }

      h1 {
        font-size: 50px;
        font-weight: bold;
      }

      button {
        background-color: #007bff;
        color: white;
        padding: 12px 24px;
        border-radius: 4px;
        border: none;
        margin-top: 20px;
        cursor: pointer;
        font-size: 20px;
        font-weight: bold;
      }
      li {
        justify-content: center;
        align-items: center;
      }

      button:hover {
        background-color: #0056b3;
      }
      label {
        font-size: 16px;
        font-weight: bold;
      }
      input {
        padding: 12px 24px;
        border-radius: 4px;
        border: none;
        margin-top: 20px;
        cursor: pointer;
        font-size: 20px;
        font-weight: bold;
        margin: 0 auto;
      }
      p {
        font-size: 16px;
        font-weight: bold;
        text: center
      }
      ul {
        list-style-position: inside;
      }
      .group-info {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        padding: 20px;
        background-color: trasparent;
        border-radius: 5px;
        }
        
        .title {
        font-size: 24px;
        font-weight: bold;
        margin-bottom: 10px;
        }
        
        .info {
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        }
        
        .card {
          width: 35%;
          margin: 0 auto; 
          padding: 20px;
          margin: auto;
          text-align: center;
          background-color: #66AA33;
          color: white;
          border-radius: 5px;
          box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
          max-width: 600px;
          border-radius: 35px;   
        }
        @media (max-width: 767px) {
          .card {
            width: 300px; /* Set width to 100% to fill the screen */
            margin: 20px 0; /* Set top and bottom margin to 20px, and remove horizontal margin */
            padding: 10px; /* Maintain the same padding */
            margin: 0 auto;
          }
        }
        @media (max-width: 767px) {
          .card-header {
            padding: 5px;
          }
        }
        @media (max-width: 767px) {
          input {
            width: 200px; /* Set width to 100% to fill the screen */
           
            padding: 10px; /* Maintain the same padding */
            margin: 0 auto;
          }
        }
        .card-header {
          font-size: 24px;
          padding: 10px;
          background-color: #66AA33;
          color: #fff;
          border-top-left-radius: 5px;
          border-top-right-radius: 5px;
          
        }
        
        .card-body {
          padding: 0px;
          
        }
        
        .subtitle {
          font-size: 18px;
          font-weight: bold;
          margin-bottom: 5px;
        }
        
        .value {
          font-size: 14px;
          margin-top: 0;
          margin-bottom: 20px;
        }
        
        .members {
          list-style: none;
          margin: 0;
          padding: 0;
          font-size: 16px;
        }
        
        .members li {
          margin-bottom: 5px;
        }
        
        #change_button {
          background-color: black;
          border-radius: 10px;
        }
        .button-group {
          display: flex;
          flex-wrap: wrap;
          justify-content: center;
          align-items: center;
          text-align: center;
        }
        
        .button-group button {
          flex: 1 1 auto;
          margin: 5px;
          width: 300px;
          border-radius: 35x;
        }

      .generic_button {
        display: block;
        background-color: #66AA33;
        color: white;
        padding: 12px 24px;
        border-radius: 35px;
        border: none;
        margin: 5px;
        cursor: pointer;
        font-size: 20px;
        font-weight: bold;
      }
        
    </style>
  </head>
  <body>
    
      <h1>Group Hub</h1>
      <h3>You must create a group before changing the name</h3>
     
      <div class="button-group">
        <div class="text-center">
      <a href="/home"><button class="generic_button">Home🏠</button></a>
      <a href="{{ url_for('auth.generate_code') }}"
        ><button class="generic_button">Create Group👥🆕</button></a>
      <a href="{{ url_for('auth.join_group') }}"><button class="generic_button">Join Group👥</button></a>
      <a href="{{ url_for('auth.leave_group') }}"
        ><button class="generic_button">Leave Group🚪</button></a
      >
      <a href="/shared_favorites" align="center">
        <button align="center" type="button" class="generic_button">
          Matched Playlst 🔥
        </button> </a>
      </div>
     
    </div>
    <div class="center">
      {% if current_user.family %}
      <br/>
      
      <br/>
      <div class="card">
        <div class="card-header">
          Group Information
          <div class="card-body">
          <p class="subtitle">Group Name</p>
          <p class="value">{{ current_user.family.name }}</p>
          {% if current_user.family.code %}
          <p class="subtitle">Group Code</p>
          <p class="value">{{ current_user.family.code }}</p>
          {% else %}
          <p class="subtitle">Group Code</p>
        
          <p class="value">No code for this group</p>
          
          {% endif %}
          {% if current_user.family.members %}
          <p class="subtitle">Members</p>
          <ul class="members">
            {% for member in current_user.family.members %}
            {% if member.photo %}
            <li> <img src="{{ url_for('static', filename='uploads/' + member.photo.filename) }}" class="avatar"> {{ member.first_name }} {{ member.last_name }} </li>
              {% else %}
              <li> {{ member.first_name }} {{ member.last_name }}  </li>
            {% endif %}

            {% endfor %}

          </ul>    
          {% else %}
          <p class="subtitle">Members</p>
          <p class="value">No members in this group yet</p>
          {% endif %}
          {% endif %}
        </div>
      </div>
      <div class="container">
        <form action="{{ url_for('auth.generate_code') }}" method="POST">
          <div class="center">
            <input type="text" id="group_name" name="group_name" required placeholder="Enter group name">
            <button type="submit" id="change_button">Change</button>
          </div>
        </form>
      </div>
    </div>
  </body>
</html>
{% endblock %}

website/templates/join_group.html
{% extends "base.html" %} {% block title %}Join Group{% endblock %} {% block
content %}
<br/>
<h1>Join Group</h1>


<form method="post" action="{{ url_for('auth.add_member') }}">
  <div class="form-group">
   
    <input
      type="text"
      id="code"
      name="code"
      class="form-control"
      placeholder="Enter group code"
      required
    />
  </div>
  <button type="submit">Join</button>
</form>


<style> 

  
  .container {
    margin: 0 auto;
    text-align: center;
  }

  h1 {
    font-size: 50px;
    font-weight: bold;
  }

  li {
    justify-content: center;
    align-items: center;
  }

  button:hover {
    background-color: #0056b3;
  }
  label {
    font-size: 16px;
    font-weight: bold;
  }
  input {
    padding: 12px 24px;
    border-radius: 4px;
    border: none;
    margin-top: 20px;
    cursor: pointer;
    font-size: 20px;
    font-weight: bold;
  }
  p {
    font-size: 16px;
    font-weight: bold;
    text: center
  }
  ul {
    list-style-position: inside;
  }
  .group-info {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 20px;
    background-color: trasparent;
    border-radius: 5px;
    }
    
    .title {
    font-size: 24px;
    font-weight: bold;
    margin-bottom: 10px;
    }
    
    .info {
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    }
    
    .card {
      width: 35%;
      margin: 0 auto; 
      padding: 20px;
      margin: auto;
      text-align: center;
      background-color: #007bff;
      color: white;
      border-radius: 5px;
      box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
    }
    @media (max-width: 767px) {
      .card {
        width: 100%; /* Set width to 100% to fill the screen */
        margin: 20px 0; /* Set top and bottom margin to 20px, and remove horizontal margin */
        padding: 20px; /* Maintain the same padding */
      }
    }
    .card-header {
      font-size: 24px;
      padding: 10px;
      background-color: #007bff;
      color: #fff;
      border-top-left-radius: 5px;
      border-top-right-radius: 5px;
    }
    
    .card-body {
      padding: 20px;
    }
    
    .subtitle {
      font-size: 18px;
      font-weight: bold;
      margin-bottom: 5px;
    }
    
    .value {
      font-size: 14px;
      margin-top: 0;
      margin-bottom: 20px;
    }
    
    .members {
      list-style: none;
      margin: 0;
      padding: 0;
      font-size: 16px;
    }
    
    .members li {
      margin-bottom: 5px;
    }
    
    #change_button {
      background-color: black;
      border-radius: 10px;
    }


</style>

{% endblock %}

website/templates/movies.html
{% extends "base.html" %}
{% block title %}Random TV Shows{% endblock %}
{% block content %}

<html>

<script>
  function showFullOverview() {
    var pTag = document.querySelector('.image-container p');
    var button = document.querySelector('button[name="show_full_overview"]');
    if (pTag.classList.contains('full-overview')) {
      pTag.classList.remove('full-overview');
      button.textContent = 'show more...';
    } else {
      pTag.classList.add('full-overview');
      button.textContent = 'show less...';
    }
  }

  
  </script>
  
  <h1 color="#000000" align="center">Movies</h1>

  <div class="container">
    <div class="image-container">
      <img src="{{ full_path_random_title_image }}" class="movie_image"/>
      {% if full_overview %}
      <p>{{ full_overview }}</p>
      {% else %}
      <p>{{ short_over_view }}</p>
      {% endif %}
   
    </div>
    
    <div class="button-container">
      <form method="post" action="{{ url_for('auth.add_favorite_movie') }}">
        <button name="favorites" type="submit" value="favorites">+Playlist</button>
        <input type="hidden" name="movie_title" value="{{ title }}" />
        <input type="hidden" name="movie_image_url" value="{{ full_path_random_title_image }}">
        <input type="hidden" name="current_user" value="{{ current_user }}">
      </form>
      
      <form method="post" action="{{ url_for('auth.movies') }}">
        <button name="next" type="submit">Next</button>
      </form>

      

    </div>
  </div>

  
    

</html>

<style>

  /* ... existing styles ... */
  .image-container p.full-overview {
    max-height: none;
  }

  h1 {
    text-align: center;
    font-family: BaronNeue, classic sans serif;
    font-size: 50px;
    font-weight: bold;
    color: #66aa33;
    margin-top: 0px;
    margin-bottom: 0px;
  }

  .container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    margin-top: 0px;
  }
  
  .image-container {
    position: relative;
  }
  
  .movie_image {
    border-radius: 35px;
    height: 500px;
    width: 400px;
  }
  
  p {
    font-size: 12px;
    line-height: 1.5;
    margin: 0px 0;
    color: black;
    max-width: 400px;
    font-family: Arial, sans-serif;
    margin: 0 10px;
    background-color: white;
    border-radius: 35px;
    margin: 0 auto;
    padding: 1px;
    text-align: center;     
  }
  
  .button-container {
    display: flex;
    align-items: center;
    justify-content: center;
    margin-top: 10px;
  }
  
  button[name="next"], button[name="favorites"] {
    margin: 0 10px;
    padding: 10px;
    font-weight: bold;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    color: white;
    background-color: #66aa33;
    position: absolute;
    bottom: -25px;
    transform: translateX(-50%);
  }

  button[name="show_full_overview"] {
   font-size: 12px;
  }
  
  button[name="next"] {
    left: 55%;
    bottom: 10px;
  }
  
  button[name="favorites"] {
    right: 45%;
    bottom: 10px;
  }
  @media screen and (max-width: 767px) {
    button[name="next"],
    left: 65%;
    button[name="favorites"] {
      right: 30%;
      position: relative;
      margin: 0 auto;
      display: block;
      bottom: 0;
    }
    p {
      margin-bottom: 60px;
    }
  }
  
</style>

{% endblock %}

website/templates/shared_favorites.html
{% extends "base.html" %}
{% block content %}
<html>
<br />
<h1 class="text-center">Matches 🔥</h1>
{% if favorites %}
<ul>

  <div class="row row-cols-1 row-cols-md-2 g-4 justify-content-center">
    {% for favorite in favorites %}
    <div class="col-6">
      <div class="card">

        <input type="hidden" name="title" value="{{ favorite.title }}" />
        <input type="hidden" name="image" value="{{ favorite.image }}" />
        <input type="hidden" name="current_user" value="{{ current_user }}" />



        <img
          src="{{ favorite.image }}"
          alt="{{ favorite.title }}"
          class="title_image"
        />
        <h5>{{ favorite.title }}</h5>
      </div>
    </div>

    {% endfor %}
  </div>
{% else %}
<p>No matches yet ☹️ come back later when you add more to your Playlst!</p>
{% endif %}
</html>

<style>

  h2 {
    margin-top: 30px;
    border-radius: 5px;
    font-family: BaronNeue, classic sans serif;
    font-size: 24px;
    font-weight: bold;
    color: #66aa33;
  }
  .card {
    border-radius: 35px;
    background-color: white;
    position: relative;
    padding-bottom: 0px;
    padding-top: 0px;
  }
  .card-header {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    padding: 10px;
    background-color: rgba(255,255,255,0.7);
    z-index: 1;
  }
  .card-body {
    padding: 30px;
  }
  .col {
    margin-bottom: 20px;
    margin-left: 5px;
  }
  .card-text {
    font-size: 16px;
  }

  .card {
    position: relative;
  }
  .title_image {
    border-top-left-radius: 35px;
    border-top-right-radius: 35px;
  }
  p {
    font-family: BaronNeue, classic sans serif;
    text-align: center;
  }

  .delete-btn {
    position: absolute;
    top: -10px;
    right: 5px;
    background-color: transparent;
    color: white;
    border: none;
    border-radius: 50%;
    width: 30px;
    height: 30px;
    font-size: 20px;
    line-height: 20px;
    text-align: center;
    padding: 0;
    cursor: pointer;
  }
</style>

{% endblock %}

website/templates/tvshows.html
{% extends "base.html" %} {% block title %}Random TV Shows{% endblock %} {%
block content %}

<html>
  <h1 color="#000000" align="center">Streaming</h1>

  <div class="container">
    <div class="image-container">
      <img src="{{ full_path_random_title_image }}" class="movie_image" />
      <p>{{ over_view }}</p>
    </div>

    <div class="button-container">
      <form method="post" action="{{ url_for('auth.add_favorite_tv_show') }}">
        <button name="favorites" type="submit" value="favorites">
          +Playlist
        </button>
        <input type="hidden" name="tv_show_title" value="{{ title }}" />
        <input
          type="hidden"
          name="tv_show_image_url"
          value="{{ full_path_random_title_image }}"
        />
        <input type="hidden" name="current_user" value="{{ current_user }}" />
      </form>

      <form method="post" action="{{ url_for('auth.tvshows') }}">
        <button name="next" type="submit">Next</button>
      </form>
    </div>
  </div>
</html>

<style>
  h1 {
    text-align: center;
    font-family: BaronNeue, classic sans serif;
    font-size: 50px;
    font-weight: bold;
    color: #66aa33;
    margin-top: 0px;
    margin-bottom: 0px;
  }

  .container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    margin-top: 0px;
  }

  .image-container {
    position: relative;
  }

  .movie_image {
    border-radius: 35px;
    height: 500px;
    width: 400px;
  }

  p {
    font-size: 12px;
    line-height: 1.5;
    margin: 0px 0;
    color: black;
    max-width: 400px;
    font-family: Arial, sans-serif;
    margin: 0 10px;
    background-color: white;
    border-radius: 35px;
    margin: 0 auto;
    padding: 1px;
    text-align: center;
  }

  .button-container {
    display: flex;
    align-items: center;
    justify-content: center;
    margin-top: 10px;
  }

  button[name="next"], button[name="favorites"] {
    margin: 0 10px;
    padding: 10px;
    font-weight: bold;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    color: white;
    background-color: #66aa33;
    position: absolute;

    top:
    transform: translateX(-50%);
  }

  button[name="next"] {
    left: 55%;
    bottom: 100px;
  }

  button[name="favorites"] {
    right: 45%;
    bottom: 100px;
  }

  @media screen and (max-width: 767px) {
    button[name="next"],
    left: 65%;
    button[name="favorites"] {
      right: 30%;
      position: relative;
      margin: 0 auto;
      display: block;
      bottom: 0;
    }
    p {
      margin-bottom: 60px;
    }
  }
</style>

{% endblock %}